### ISSUE TITLE
i can not use in dopus v12.25

### ISSUE THREAD

**Issue by laoqiuqiu** [TheZoc/ZPatchViewer#1]
Can you check it?

**Comment by TheZoc** [comment]
Hi @laoqiuqiu,

[There's currently a bug with Directory Opus](https://resource.dopus.com/t/creating-a-simple-data-visualizer/26408/26), and I'll be sure to update this plugin as soon as it's updated :)

**Comment by TheZoc** [comment]
Fixed in 015ee2662fb37bad2bea9acc36852521094138a9.
Please note you need Directory Opus version 12.25.4 beta or higher to run the plugin, due to a bug in the software.

**Comment by laoqiuqiu** [comment]
Viewer implemented by VBScript

https://github.com/laoqiuqiu/DOpus-Script/blob/master/Button/ZPatch%20File%20View.dcf
